package com.wks.caseengine.cases.instance.accounts;

import java.io.Serializable;
import java.util.Optional;

public enum AccountsEventType implements Serializable {

	ACCOUNTS_INITIALIZED("ACCOUNTS_INITIALIZED"),
	BILLING_SETUP_COMPLETED("BILLING_SETUP_COMPLETED"),
	PAYMENT_METHOD_AUTHORIZED("PAYMENT_METHOD_AUTHORIZED"),
	RETAINER_FUNDED("RETAINER_FUNDED"),
	ENGAGEMENT_TERMS_COMPLETED("ENGAGEMENT_TERMS_COMPLETED"),
	ACCOUNTS_ACTIVATED("ACCOUNTS_ACTIVATED"),
	INVOICE_ISSUED("INVOICE_ISSUED"),
	PAYMENT_RECEIVED("PAYMENT_RECEIVED"),
	TRUST_DRAWDOWN_REQUESTED("TRUST_DRAWDOWN_REQUESTED"),
	TRUST_DRAWDOWN_APPROVED("TRUST_DRAWDOWN_APPROVED"),
	ACCOUNT_FLAGGED_PAST_DUE("ACCOUNT_FLAGGED_PAST_DUE"),
	COLLECTIONS_ESCALATED("COLLECTIONS_ESCALATED"),
	PAYMENT_ARRANGEMENT_RECORDED("PAYMENT_ARRANGEMENT_RECORDED"),
	ACCOUNT_RETURNED_TO_CURRENT("ACCOUNT_RETURNED_TO_CURRENT"),
	FINAL_ACCOUNT_STATEMENT_ISSUED("FINAL_ACCOUNT_STATEMENT_ISSUED"),
	FINAL_RECONCILIATION_COMPLETED("FINAL_RECONCILIATION_COMPLETED"),
	ACCOUNT_CLOSED("ACCOUNT_CLOSED"),
	HEALTH_REEVALUATED("HEALTH_REEVALUATED");

	private final String code;

	AccountsEventType(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}

	public static Optional<AccountsEventType> fromValue(String value) {
		for (AccountsEventType eventType : values()) {
			if (eventType.code.equals(value)) {
				return Optional.of(eventType);
			}
		}
		return Optional.empty();
	}
}
