package com.wks.caseengine.cases.instance.accounts;

import java.io.Serializable;
import java.util.Optional;

public enum AccountsHealthReasonCode implements Serializable {

	MISSING_BILLING_SETUP("MISSING_BILLING_SETUP"),
	MISSING_PAYMENT_METHOD("MISSING_PAYMENT_METHOD"),
	MISSING_RETAINER("MISSING_RETAINER"),
	LOW_TRUST_BALANCE("LOW_TRUST_BALANCE"),
	PAST_DUE_INVOICE("PAST_DUE_INVOICE"),
	REPEATED_PAYMENT_FAILURE("REPEATED_PAYMENT_FAILURE"),
	COLLECTIONS_ACTIVE("COLLECTIONS_ACTIVE"),
	MISSING_BILLING_CONTACT("MISSING_BILLING_CONTACT"),
	MISSING_INSTRUCTING_FIRM("MISSING_INSTRUCTING_FIRM"),
	MISSING_COUNSEL_BILLING_MODE("MISSING_COUNSEL_BILLING_MODE"),
	FINAL_RECONCILIATION_OUTSTANDING("FINAL_RECONCILIATION_OUTSTANDING"),
	MALFORMED_CONFIGURATION("MALFORMED_CONFIGURATION"),
	MISSING_MATTER_TYPE("MISSING_MATTER_TYPE"),
	MISSING_FLAT_FEE_SETUP("MISSING_FLAT_FEE_SETUP"),
	MISSING_SUBSCRIPTION_CONFIGURATION("MISSING_SUBSCRIPTION_CONFIGURATION"),
	MISSING_COUNSEL_CONFIGURATION("MISSING_COUNSEL_CONFIGURATION"),
	INVALID_BILLING_PARTY_MODEL("INVALID_BILLING_PARTY_MODEL"),
	INVALID_BILLING_MODE("INVALID_BILLING_MODE"),
	INVALID_ACCOUNTS_STATE("INVALID_ACCOUNTS_STATE"),
	INVALID_ACCOUNTS_TRANSITION("INVALID_ACCOUNTS_TRANSITION");

	private final String code;

	AccountsHealthReasonCode(String code) {
		this.code = code;
	}

	public String getCode() {
		return code;
	}

	public static Optional<AccountsHealthReasonCode> fromValue(String value) {
		for (AccountsHealthReasonCode reasonCode : values()) {
			if (reasonCode.code.equals(value)) {
				return Optional.of(reasonCode);
			}
		}
		return Optional.empty();
	}
}
